specs:
  hostname: smile.sparked-fhir.com
volumeConfig:
  cdr:
    amq:
      sizeLimit: 100Mi
image:
  repository: docker.smilecdr.com/smilecdr
  imagePullSecrets:
  - type: sscsi
    provider: aws
    secretArn: arn:aws:secretsmanager:ap-southeast-2:471112546300:secret:example-key-value-x7qP8R
serviceAccount:
  create: true
mappedFiles:
  package-aubase.json:
    path: /home/smile/smilecdr/classes/config_seeding
  package-aucore-2.0.0-preview.json:
    path: /home/smile/smilecdr/classes/config_seeding
  package-auereq-1.0.0.json:
    path: /home/smile/smilecdr/classes/config_seeding
  package-au-patient-summary-0.4.0-draft.json:
    path: /home/smile/smilecdr/classes/config_seeding
  package-international-patient-summary-2.0.0.json:
    path: /home/smile/smilecdr/classes/config_seeding
  package-aubase-6.0.0-preview.json:
    path: /home/smile/smilecdr/classes/config_seeding
secrets:
  usersConfig:
    name: smilecdr-users-json
    type: sscsi
    provider: aws
    secretName: smilecdr-users-json
    secretArn: arn:aws:secretsmanager:ap-southeast-2:471112546300:secret:smilecdr-users-json-IInyPo
    secretKeyMap:
      users-json:
        secretKeyName: content
        k8sSecretKeyName: users-json
        mountSpec:
          mountPath: /home/smile/smilecdr/classes/config_seeding/users.json
          subPath: users-json
copyFiles:
  customerlib:
    sources:
    - type: s3
      bucket: examplebucket-fhir-aws
      path: /smile/hapi-aups-generator-0.1.0-alpha.jar
resources:
  requests:
    cpu: '1'
  limits:
    memory: 6Gi
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: karpenter.sh/capacity-type
          operator: In
          values:
          - on-demand
observability:
  enabled: false
podAnnotations:
  instrumentation.opentelemetry.io/inject-java: 'true'
extraEnvVars:
- name: OTEL_EXPORTER_OTLP_ENDPOINT
  value: http://k8s-monitoring-alloy-metrics.monitoring.svc.cluster.local:4317
- name: OTEL_EXPORTER_OTLP_PROTOCOL
  value: grpc
- name: OTEL_METRICS_EXPORTER
  value: otlp
- name: OTEL_LOGS_EXPORTER
  value: otlp
- name: OTEL_TRACES_EXPORTER
  value: otlp
- name: OTEL_SERVICE_NAME
  value: smilecdr
- name: OTEL_RESOURCE_ATTRIBUTES
  value: service.name=smilecdr,service.namespace=smilecdr
- name: OTEL_INSTRUMENTATION_METHODS_INCLUDE
  value: ca.uhn.hl7v2.app.Responder[processMessage];ca.cdr.broker.kafka.channel.CdrKafkaAcknowledgingListener[onMessage]
